[tool.poetry]
name = "transfermarkt-api"
version = "0.1.0"
description = ""
authors = ["Felipe Allegretti <felipe@allegretti.me>"]
license = "MIT"
readme = "README.md"
packages = [{include = "transfermarkt_api"}]

[tool.poetry.dependencies]
python = "^3.9"
lxml = "4.9.2"
beautifulsoup4 = "4.11.1"
requests = "2.28.2"

[tool.poetry.group.dev.dependencies]
black = "23.1.0"
isort = "5.12.0"
jupyter = "1.0.0"

[tool.black]
line-length = 120
verbose = true
preview = true

[tool.isort]
profile = "black"